# Site settings
title: Hackin' Omics
description: August 5-6, 2022
owner: U-BRITE # or company name
first_published: 2022 # if migrating another site, the year of your first publish
email: nafisahsani@uabmc.edu
baseurl: "/ubrite-hackathon-2022" # the subpath of your site, e.g. /blog
url: "https://www.shauritahutchins.com" # the base hostname & protocol for your site
hashtag: "#HackinOmics22"

social:
  github: https://github.com/informaticsclub
  twitter: https://twitter.com/InformaticsUAB
  #linkedin-square: https://www.linkedin.com/company/9501702
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:tmamidi@uab.edu
  #flickr:
  #instagram:

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts

# Build settings
markdown: kramdown
#sass:
#  style: compressed

collections:
  programmes:
    output: true
    permalink: /:collection/:path/
  landings:
    output: true
    permalink: /:collection/:path/
  committee:
    output: true
    permalink: /:collection/:path/
  projects:
    output: false
    permalink: /:collection/:path/
