# Welcome to Jekyll!
#

# Site settings
title: Hackin' Omics
description: August 5-6, 2022
owner: U-BRITE # or company name
first_published: 2022 # if migrating another site, the year of your first publish
email: nafisahsani@uabmc.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.shauritahutchins.com/ubrite-hackathon-2022/" # the base hostname & protocol for your site
social:
  hashtag_link: https://twitter.com/hashtag/#HackinOmics22
  hashtag: https://twitter.com/hashtag/#HackinOmics22
  GitHub: https://github.com/informaticsclub
  Twitter:https://twitter.com/InformaticsUAB
  #linkedin-square: https://www.linkedin.com/company/9501702
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:tmamidi@uab.edu
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts

# Build settings
markdown: kramdown
#sass:
#  style: compressed

collections:
  programmes:
    output: true
    permalink: /:collection/:path/
  landings:
    output: true
    permalink: /:collection/:path/
  committee:
    output: true
    permalink: /:collection/:path/
  projects:
    output: false
    permalink: /:collection/:path/
